### ISSUE TITLE
Image creation with justified layout needs optimization for unusual aspect ratios

### ISSUE THREAD

**Issue by SerenaButler** [LycheeOrg/Lychee-v3#142]
Some pictures are partially displayed with a "wrong" aspect ratio and are distorted accordingly. This happen when the aspect ration is rather unusual as it was manual adjusted.

Please check here: https://lychee.indee.de/#15136146003600

**Comment by ildyria** [comment]
The justified algorithm is directly taken from https://github.com/flickr/justified-layout
So we cannot really change anything about that.

**Comment by SerenaButler** [comment]
As a workaround:

```css
.justified-layout>.photo>.thumbimg, .justified-layout>.photo>.thumbimg>img {
    object-fit: cover;
}
```
