### ISSUE TITLE
user.css not working

### ISSUE THREAD

**Issue by SerenaButler** [LycheeOrg/Lychee-v3#159]
Unfortunately css code in user.css has no effect:

My Code (I allready tried with "!important" even I think this shoul not be needed):

```css
body {
    line-height: 1 !important;
    background-color: #4c4c4c !important;
    font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif !important;
	font-family: 'Open Sans', Helvetica, Arial, sans-serif !important;
	font-style: normal !important;
	font-variant: normal !important;
	font-weight: 100 !important;
	line-height: 26.4px !important;
	font-size: 12px !important;
    -webkit-font-smoothing: antialiased !important;
    -moz-font-smoothing: antialiased !important;
    -moz-osx-font-smoothing: grayscale !important;
    font-smoothing: antialiased
}

.content .album .thumbimg,.content .photo .thumbimg{
    position:absolute !important;
    width:200px !important;
    height:200px !important;
    background:#222 !important;
    color:#222 !important;
    -webkit-box-shadow:5px 4px 10px rgba(0, 0, 0, .5) !important;
    box-shadow:5px 4px 10px rgba(0, 0, 0, .5) !important;
    border:4px solid #FFF !important;
    -webkit-transition:opacity .3s ease-out,border-color .3s ease-out,-webkit-transform .3s ease-out !important;
    transition:opacity .3s ease-out,transform .3s ease-out,border-color .3s ease-out,-webkit-transform .3s ease-out !important;
    -o-transition:opacity .3s ease-out,transform .3s ease-out,border-color .3s ease-out
}

.content .album .overlay,.content .photo .overlay{
    position:absolute !important;
    margin:-2px 4px !important;
    width:200px !important;
    background:-webkit-gradient(linear,left top,left bottom,from(rgba(0,0,0,0)),to(rgba(0,0,0,.6))) !important;
    background:-webkit-linear-gradient(top,rgba(0,0,0,0),rgba(0,0,0,.6)) !important;
    background:-o-linear-gradient(top,rgba(0,0,0,0),rgba(0,0,0,.6)) !important;
    background:linear-gradient(to bottom,rgba(0,0,0,0),rgba(0,0,0,.6)) !important;
    bottom:1px
}


.content .divider h1 {
    font-size: 30px !important;
    text-shadow: rgba(255, 255, 255, 0.3) -1px -1px 0px, rgba(0, 0, 0, 0.8) 1px 1px 0px !important;
    color: rgb(51, 51, 51) !important;
    opacity: 0.5 !important;
    margin: 0px 0px 0px 30px !important;
	font-weight:100
}

.header {
    position: fixed !important;
    height: 49px !important;
    width: 100% !important;
    background: linear-gradient(to bottom, #444, #1a1a1a) !important;
    border-bottom: 1px solid #000 !important;
    z-index: 1 !important;
    transition: -webkit-transform .3s ease-out !important;
    transition: transform .3s ease-out !important;
    transition: transform .3s ease-out, -webkit-transform .3s ease-out !important;
    box-shadow: 5px 4px 10px rgba(0, 0, 0, .5) !important;
}

.header__title{
    width:100% !important;
    padding:16px 0 !important;
    color:#fff !important;
    font-size:22px !important;
    font-weight:100 !important;
    text-align:center !important;
    cursor:default !important;
    overflow:hidden !important;
    white-space:nowrap !important;
    -o-text-overflow:ellipsis !important;
    text-overflow:ellipsis !important;
    -webkit-transition:margin-left .5s !important;
    -o-transition:margin-left .5s !important;
    transition:margin-left .5s
}


.basicModal .select{
    display:inline-block !important;
    position:relative !important;
    margin:1px 5px !important;
    padding:0 !important;
    width:110px !important;
    background:rgba(0,0,0,.3) !important;
    color:#fff !important;
    border-radius:3px !important;
    border:1px solid rgba(0,0,0,.2) !important;
    -webkit-box-shadow:0 1px 0 rgba(255,255,255,.02) !important;
    box-shadow:0 1px 0 rgba(255,255,255,.02) !important;
    font-size:11px !important;
    line-height:16px !important;
    overflow:hidden !important;
    outline:0 !important;
    vertical-align:middle
}

#image {
  transition: none !important;
}
```

It seems user.css is just not loading. Can't see it anyway in  Chrome Inspector though.

**Comment by ildyria** [comment]
Sorry @SerenaButler I thought I added that missing line, but it seems that I forgot about it (I did add it on the v4).

It should be fixed now.

**Comment by ildyria** [comment]
@SerenaButler on a side note, you might want to add:
```css
#image {
  animation-name: none !important;
  animation-duration: 0 !important;
}
```

;)

Also quick tip: after the ` ``` ` I added `css` : ` ```css` to enable the syntax coloring of the block, I updated your issue with it. :p
